# Site
title: NAU Code
description: Nau Studio code documentation hub
image: https://code.naustud.io/cover.png
url: http://code.naustud.io

# SEO
twitter:
  username: naustudio
facebook:
  publisher: nau.creative
author: naustudio

# Setup
show_downloads: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-seo-tag

google_analytics: UA-46467058-3
