title: Nau Code
description: Nau Studio code documentation hub
image: https://code.naustud.io/nau-code.png

theme: jekyll-theme-slate

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-seo-tag
